#ifndef __D3D8_H__
#define __D3D8_H__

#define D3DMXINLINE inline
#include <d3dm.h>
#include <d3dmx.h>
#include <d3dmxmath.h>
#include <d3dmtypes.h>

#pragma comment(lib, "d3dm.lib")
#pragma comment(lib, "d3dmx.lib")

#define D3D_SDK_VERSION       D3DM_SDK_VERSION

// unsupported features
#define D3DCREATE_SOFTWARE_VERTEXPROCESSING 0

#define IDirect3D8             IDirect3DMobile
#define IDirect3DDevice8       IDirect3DMobileDevice
#define IDirect3DIndexBuffer8  IDirect3DMobileIndexBuffer
#define IDirect3DSurface8      IDirect3DMobileSurface
#define IDirect3DTexture8      IDirect3DMobileTexture
#define IDirect3DVertexBuffer8 IDirect3DMobileVertexBuffer

#define Direct3DCreate8       Direct3DMobileCreate

#define D3DXMATRIX            D3DMXMATRIX
#define D3DXMatrixIdentity    D3DMXMatrixIdentity
#define D3DXMatrixMultiply    D3DMXMatrixMultiply
#define D3DXMatrixOrthoOffCenterLH D3DMXMatrixOrthoOffCenterLH
#define D3DXMatrixScaling     D3DMXMatrixScaling
#define D3DXMatrixTranslation D3DMXMatrixTranslation
#define D3DXMatrixRotationZ   D3DMXMatrixRotationZ
#define D3DXCreateTexture     D3DMXCreateTexture

#define D3DBACKBUFFER_TYPE_MONO D3DMBACKBUFFER_TYPE_MONO

#define D3DCLEAR_TARGET       D3DMCLEAR_TARGET
#define D3DCLEAR_ZBUFFER      D3DMCLEAR_ZBUFFER

#define D3DZB_TRUE            D3DMZB_TRUE
#define D3DERR_DEVICELOST     D3DMERR_DEVICELOST

#define D3DPOOL_DEFAULT       D3DMPOOL_VIDEOMEM

#define D3DDISPLAYMODE        D3DMDISPLAYMODE
#define D3DADAPTER_DEFAULT    D3DMADAPTER_DEFAULT

#define D3DFMT_D16            D3DMFMT_D16
#define D3DFMT_INDEX16        D3DMFMT_INDEX16
#define D3DFMT_R5G6B5         D3DMFMT_R5G6B5
#define D3DFMT_X8R8G8B8       D3DMFMT_X8R8G8B8

#define D3DBLEND_SRCALPHA     D3DMBLEND_SRCALPHA
#define D3DBLEND_INVSRCALPHA  D3DMBLEND_INVSRCALPHA

#define D3DFVF_XYZ            D3DMFVF_XYZ_FLOAT
#define D3DFVF_DIFFUSE        D3DMFVF_DIFFUSE

#define D3DLOCKED_RECT        D3DMLOCKED_RECT

#define D3DPT_LINELIST        D3DMPT_LINELIST
#define D3DPT_TRIANGLELIST    D3DMPT_TRIANGLELIST

#define D3DRS_ALPHABLENDENABLE D3DMRS_ALPHABLENDENABLE
#define D3DRS_CULLMODE        D3DMRS_CULLMODE
#define D3DCULL_NONE          D3DMCULL_NONE
#define D3DRS_DESTBLEND       D3DMRS_DESTBLEND
#define D3DRS_LIGHTING        D3DMRS_LIGHTING
#define D3DRS_SRCBLEND        D3DMRS_SRCBLEND
#define D3DRS_ZENABLE         D3DMRS_ZENABLE

#define D3DTS_PROJECTION      D3DMTS_PROJECTION
#define D3DTS_VIEW            D3DMTS_VIEW

#define D3DFORMAT             D3DMFORMAT
#define D3DPRESENT_PARAMETERS D3DMPRESENT_PARAMETERS
#define D3DSWAPEFFECT_COPY    D3DMSWAPEFFECT_COPY
#define D3DVIEWPORT8          D3DMVIEWPORT
#define D3DPRESENTFLAG_LOCKABLE_BACKBUFFER D3DMPRESENTFLAG_LOCKABLE_BACKBUFFER
#define D3DDEVTYPE_HAL        D3DMDEVTYPE_DEFAULT

#define D3DERR_DEVICENOTRESET D3DMERR_DEVICENOTRESET
#define D3DFMT_UNKNOWN        D3DMFMT_UNKNOWN
#define D3DZB_FALSE           D3DMZB_FALSE
#define D3DSURFACE_DESC       D3DMSURFACE_DESC
#define D3DUSAGE_RENDERTARGET D3DMUSAGE_RENDERTARGET
#define D3DMULTISAMPLE_NONE   D3DMMULTISAMPLE_NONE
#define D3DFMT_A8R8G8B8       D3DMFMT_A8R8G8B8
#define D3DPOOL_MANAGED       D3DMPOOL_MANAGED
#define D3DLOCK_READONLY      D3DMLOCK_READONLY
#define D3DBLEND_ONE          D3DMBLEND_ONE
#define D3DRS_ZWRITEENABLE    D3DMRS_ZWRITEENABLE
#define D3DTSS_COLOROP        D3DMTSS_COLOROP
#define D3DTOP_ADD            D3DMTOP_ADD
#define D3DTOP_MODULATE       D3DMTOP_MODULATE
#define D3DADAPTER_IDENTIFIER8 D3DMADAPTER_IDENTIFIER
#define D3DENUM_NO_WHQL_LEVEL 0
#define D3DSWAPEFFECT_COPY_VSYNC D3DMSWAPEFFECT_COPY_VSYNC
#define D3DFMT_A1R5G5B5       D3DMFMT_A1R5G5B5
#define D3DSWAPEFFECT_FLIP    D3DMSWAPEFFECT_FLIP
#define D3DPRESENT_RATE_DEFAULT D3DMPRESENT_INTERVAL_DEFAULT
#define D3DPRESENT_INTERVAL_ONE D3DMPRESENT_INTERVAL_ONE
#define D3DPRESENT_INTERVAL_IMMEDIATE D3DMPRESENT_INTERVAL_IMMEDIATE
#define D3DFMT_X1R5G5B5       D3DMFMT_X1R5G5B5
#define D3DUSAGE_WRITEONLY    D3DMUSAGE_WRITEONLY
#define D3DFVF_TEX1           D3DMFVF_TEX1
#define D3DRS_ALPHATESTENABLE D3DMRS_ALPHATESTENABLE
#define D3DRS_ALPHAREF        D3DMRS_ALPHAREF
#define D3DRS_ALPHAFUNC       D3DMRS_ALPHAFUNC
#define D3DCMP_GREATEREQUAL   D3DMCMP_GREATEREQUAL
#define D3DTSS_COLORARG1      D3DMTSS_COLORARG1
#define D3DTA_TEXTURE         D3DMTA_TEXTURE
#define D3DTSS_COLORARG2      D3DMTSS_COLORARG2
#define D3DTA_DIFFUSE         D3DMTA_DIFFUSE
#define D3DTSS_ALPHAOP        D3DMTSS_ALPHAOP
#define D3DTSS_ALPHAARG1      D3DMTSS_ALPHAARG1
#define D3DTSS_ALPHAARG2      D3DMTSS_ALPHAARG2
#define D3DTSS_MIPFILTER      D3DMTSS_MIPFILTER
#define D3DTEXF_POINT         D3DMTEXF_POINT
#define D3DTSS_MAGFILTER      D3DMTSS_MAGFILTER
#define D3DTEXF_LINEAR        D3DMTEXF_LINEAR
#define D3DTSS_MINFILTER      D3DMTSS_MINFILTER

#define LPDIRECT3DSURFACE8    LPDIRECT3DMOBILESURFACE
#define LPDIRECT3DTEXTURE8    LPDIRECT3DMOBILETEXTURE

#endif

